from __future__ import annotations

import importlib.util
from pathlib import Path


SCRIPT_PATH = (
    Path(__file__).resolve().parents[1] / "scripts" / "xml_identical_validation.py"
)
_spec = importlib.util.spec_from_file_location("xml_identical_validation", SCRIPT_PATH)
assert _spec is not None
assert _spec.loader is not None
xml_identical_validation = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(xml_identical_validation)


def test_compare_namespace_bindings_ignores_mv_and_pos_prefixes(
    tmp_path: Path,
) -> None:
    _left_path = tmp_path / "left.xml"
    _right_path = tmp_path / "right.xml"

    _left_path.write_text(
        """<?xml version="1.0" encoding="UTF-8"?>
<unit xmlns="http://www.srcML.org/srcML/src"
      xmlns:diff="http://www.srcML.org/srcDiff">
  <diff:delete><name>old</name></diff:delete>
</unit>
""",
        encoding="utf-8",
    )
    _right_path.write_text(
        """<?xml version="1.0" encoding="UTF-8"?>
<unit xmlns="http://www.srcML.org/srcML/src"
      xmlns:diff="http://www.srcML.org/srcDiff"
      xmlns:ns1="http://www.srcML.org/srcML/position"
      xmlns:ns3="http://www.srcML.org/srcMove"
      ns1:tabs="8">
  <diff:delete ns3:id="abc" ns1:start="1:1" ns1:end="1:2"><name>old</name></diff:delete>
</unit>
""",
        encoding="utf-8",
    )

    _namespace_mismatch = xml_identical_validation.compare_namespace_bindings(
        _left_path,
        _right_path,
    )
    _left_root = xml_identical_validation.parse_xml(_left_path)
    _right_root = xml_identical_validation.parse_xml(_right_path)
    _left_ignored_uris = xml_identical_validation.collect_ignored_namespace_uris(
        _left_path
    )
    _right_ignored_uris = xml_identical_validation.collect_ignored_namespace_uris(
        _right_path
    )

    assert _namespace_mismatch is None
    assert (
        xml_identical_validation.compare_elements(
            _left_root,
            _right_root,
            _left_ignored_uris,
            _right_ignored_uris,
        )
        is None
    )


def test_compare_namespace_bindings_rejects_autogenerated_non_ignored_prefixes(
    tmp_path: Path,
) -> None:
    _left_path = tmp_path / "left.xml"
    _right_path = tmp_path / "right.xml"

    _left_path.write_text(
        """<?xml version="1.0" encoding="UTF-8"?>
<unit xmlns="http://www.srcML.org/srcML/src"
      xmlns:diff="http://www.srcML.org/srcDiff">
  <diff:delete><name>old</name></diff:delete>
</unit>
""",
        encoding="utf-8",
    )
    _right_path.write_text(
        """<?xml version="1.0" encoding="UTF-8"?>
<ns0:unit xmlns:ns0="http://www.srcML.org/srcML/src"
          xmlns:ns1="http://www.srcML.org/srcML/position"
          xmlns:ns2="http://www.srcML.org/srcDiff"
          ns1:tabs="8">
  <ns2:delete><ns0:name>old</ns0:name></ns2:delete>
</ns0:unit>
""",
        encoding="utf-8",
    )

    _mismatch = xml_identical_validation.compare_namespace_bindings(
        _left_path,
        _right_path,
    )

    assert _mismatch is not None
    assert "Namespace binding mismatch" in _mismatch
    assert "ns0" in _mismatch
    assert "ns2" in _mismatch
